### ISSUE TITLE
Exit status reflects a clean or failed run

### ISSUE THREAD

**Issue by twinn** [nccgroup/sobelow#3]
Thank you so much for this project, this literally could save me from having to quit my job.

Currently `mix sobelow` will always exit with a status of 0 even when issues were discovered. This makes using this tool as part of a ci pipeline difficult. This maybe ought to be configurable via a flag that lets you set the severity of issue that would trigger the non-zero exit status.

I'm happy to take a crack at this but the change is going to touch a lot of places as currently each check only returns `:ok` from `Enum.each`, also want to get some test coverage in place as well to validate functionality and was wondering if you had considered a strategy for that (a fixture folder with different phoenix apps in it?).

Thanks again!

**Comment by GriffinMB** [comment]
Glad you're finding it useful :)

I'll work on adding a flag for non-zero exit statuses. I'm doing some codebase reorganization this week, so it probably isn't the ideal time to help out on larger updates!

As for tests, I actually do have a body of Phoenix apps that I use for testing. Unfortunately, a number of them have severe vulnerabilities that I don't want to expose before I'm able to get in touch with the repo owners. Maybe it would be a good idea to write some general running/diffing tests that can work with any folder of apps, and let people assemble their own test apps? I'm also working on building a vulnerable app which could serve as a simple test.

**Comment by michalmuskala** [comment]
I saw some tools defining a bit flag of possible kind of issues and having the final exit status be the and of all the detected ones. I'm not sure how useful that feature is in general, though.

**Comment by GriffinMB** [comment]
Hey @twinn, I pushed an update for this. You can now use the `exit` flag which accepts a confidence threshold (low, medium, or high), and will return a non-zero exit status (1) above that threshold.

For example: `mix sobelow --exit Low` will have a non-zero exit status for low, medium, and high confidence findings.

It's pretty simple for now, because I'd like to see how it's used, but I've built the feature to allow for additional functionality if it proves to be wanted/needed. For example, I quite like @michalmuskala's idea, but it would be nice to know if that is something that would prove to be useful.

Thanks again for the report!
