### ISSUE TITLE
Add flag for scanning multiple applications

### ISSUE THREAD

**Issue by GriffinMB** [nccgroup/sobelow#31]
Useful for umbrella projects or research.

**Comment by karolsluszniak** [comment]
Hey @GriffinMB, I've recently included Sobelow as one of [curated checks in the `mix check` task](https://hexdocs.pm/ex_check/Mix.Tasks.Check.html#module-tools) in order to make it more visible in the Elixir ecosystem (it took myself long enough to discover it...).

What's important for this issue is that not long after I've discovered that it doesn't work at all (by raising `FunctionClauseError` on `Utils.binarize_app_name`) when executed from the root of an umbrella project. As I understand, this issue (as well as several linked ones) is here in hope to address that limitation. So for those having this issue I'd like to report that **Sobelow works perfectly fine in umbrella projects right out of the box when used with `mix check` task provided by [ex_check package](https://hex.pm/packages/ex_check)**. Hope that helps those wanting to use Sobelow in larger projects - which usually need security checking more than the others - until the issue is addressed in the library. 

Btw it works because `mix check` has its own layer for recursion over umbrella child apps and I've updated Sobelow's stock configuration to mark it as a recursive tool (in https://github.com/karolsluszniak/ex_check/blob/master/lib/ex_check/config/default.ex#L10) even though `mix sobelow` doesn't have the `@recursive true` flag (I'm not sure why - I do believe that Sobelow needs to recurse over umbrella apps one way or another e.g. to properly check multiple web applications in single umbrella).

**Comment by GriffinMB** [comment]
If you want to make a PR adding `@recursive true`, that sounds like a fine option to me. Otherwise, I will make the update ahead of the next release.

> raising FunctionClauseError on Utils.binarize_app_name

That error is addressed in a previous commit, so will no longer be so ugly in the future :)

**Comment by GriffinMB** [comment]
This has been added and will be available in the next release. Thanks!
