### ISSUE TITLE
Support Phoenix.Controller.html#put_secure_browser_headers/2 method in Sobelow.Config.CSP check

### ISSUE THREAD

**Issue by akrisanov** [nccgroup/sobelow#38]
Hi! I've just started to use Sobelow in my Phoenix application and got confused about CSP check. Before adding any additional headers I ran `mix sobelow --config` and got following failure:

```shell
Missing Content-Security-Policy - High Confidence
Pipeline: browser:5


pipeline(:browser) do
  plug(:accepts, ["html"])
  plug(:fetch_session)
  plug(:fetch_flash)
  plug(:protect_from_forgery)
  plug(:put_secure_browser_headers)
end
```

I decided to go with a separate Plug for CSP and define two security headers Plugs in `router.ex`:

```elixir
pipeline(:browser) do
  plug(:accepts, ["html"])
  plug(:fetch_session)
  plug(:fetch_flash)
  plug(:protect_from_forgery)
  plug(:put_secure_browser_headers)
  plug(MyAppWeb.CSPHeader)
end
```

**myapp/lib/myapp_web/plugs/csp_header.ex**:

```elixir
defmodule MyAppWeb.CSPHeader do
  @moduledoc """
  Plug to set Content-Security-Policy with websocket endpoints
  """

  alias Phoenix.Controller
  alias Plug.Conn

  def init(opts), do: opts

  def call(conn, _opts) do
    Controller.put_secure_browser_headers(conn, %{
      "content-security-policy" => "\
        connect-src 'self' #{websocket_endpoints(conn)}; \
        default-src 'self';\
        script-src 'self' 'unsafe-inline' 'unsafe-eval';\
        style-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com;\
        img-src 'self' 'unsafe-inline' 'unsafe-eval' data:;\
        font-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.gstatic.com data:;\
      "
    })
  end

  defp websocket_endpoints(conn) do
    host = Conn.get_req_header(conn, "host")
    "ws://#{host} wss://#{host}"
  end
end
```

**.sobelow-config**:

```yml
[
  verbose: true,
  private: false,
  skip: false,
  router: "",
  exit: "Low",
  format: "txt",
  ignore: [""],
  ignore_files: [
    "config/prod.secret.exs"
  ]
]
```

I thought Sobelow would also check `Phoenix.Controller.html#put_secure_browser_headers/2` in my custom plug, but it's not true. I still have a failure.

Is it any rational workaround for such case? Is it make sense to extend Sobelow to support `Phoenix.Controller.html#put_secure_browser_headers/2`?

Thanks!

**Comment by GriffinMB** [comment]
Hi, thanks for opening this issue! 

Sobelow checks inline in the pipeline itself for the `put_secure_browser_headers` function. The tool doesn't attempt to resolve arbitrary functions and modules, since that would necessitate maintaining state in a way that's a bit too compiler-like. 

Adjusting the pipeline will suppress the finding:

```elixir
pipeline(:browser) do
  plug(:accepts, ["html"])
  plug(:fetch_session)
  plug(:fetch_flash)
  plug(:protect_from_forgery)
  plug(:put_secure_browser_headers, %{"content-security-policy" => your_content_security_policy })
end
```

Also, you should feel free to ignore false positives! Sobelow will attempt to aggressively flag anything that could be vulnerable, so any large or complex project will tend to have a handful of false positives. Once you've validated them, you should just add them to the ignore list or use the skip functionality. In this case, you can add "Config.CSP" to the .sobelow-config ignore list. 

All of this said, I do think dropping the confidence rating in the presence of custom plugs makes sense. So that is something I will investigate.

**Comment by akrisanov** [comment]
> Once you've validated them, you should just add them to the ignore list or use the skip functionality. In this case, you can add "Config.CSP" to the .sobelow-config ignore list.

Yes, it's what I did recently.

Thanks for your answer @GriffinMB
